project:
  type: website

website:
  title: "qaurto_website_compute_locally_render_github"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



